### ISSUE TITLE
Data Attributes is throwing a server error with the latest Fabric API

### ISSUE THREAD

**Issue by GhostRiderGrey** [CleverNucleus/DataAttributes#2]
Data Attributes is throwing a server error with the latest Fabric API (fabric-api-0.40.6+1.17).  0.40.1 works fine

**Comment by CleverNucleus** [comment]
Thanks for the heads up, I'll look into it.

**Comment by Toilet-Man** [comment]
The error can be fixed by adding **>=** before "0.40.1" in the "fabric.mod.json file in the mod .jar
Here is my modified version of the .jar with the "fix" if it can help
[dataattributes-1.0.5-1.17.1 (0.40.1 fixed).zip](https://github.com/CleverNucleus/DataAttributes/files/7308115/dataattributes-1.0.5-1.17.1.0.40.1.fixed.zip)

**`However, I'm not sure if this change is going to cause issues in the future so use at your own risk until CleverNucleus fixes the issue`**
