### ISSUE TITLE
DataAttributes + Origins = Cursed stats

### ISSUE THREAD

**Issue by itsdinkd** [CleverNucleus/DataAttributes#5]
Having more recent versions of Data Attributes, and using Origins addons like Extra Origins causes these origins to have a positive stat instead of negative without any use of DataAttributes for this individual mod/addon.

ie; Pick Inchling origin, you are supposed to have reduced hearts by 6, instead, you gain 6 hearts. Same with attack, range, etc etc. Everything that Extra Origins is reducing in its datapack, Data  Attributes is turning to positive.

**Comment by CleverNucleus** [comment]
I'll look into this; thank you for bringing it to my attention.

**Comment by CleverNucleus** [comment]
Hi there,
I've done some testing, and I actually can't replicate this. Using the mods listed below, I've selected Inchling origin and I have my hearts reduced by 6 like it's supposed to.

| **Mod** | **Version** |
|:----------|:-------------|
| Fabric API | `0.46.1+1.18` |
| Data Attributes | `1.1.5` |
| Origins | `1.3.1` |
| Pehkui | `3.1.0` |
| Extra Origins | `1.18.7` |
| Mod Menu | `3.0.0` |

Could you provide a list of the mods/datapacks that you've used when this has happened? Otherwise I'll be forced to close this issue.
Thanks.

**Comment by itsdinkd** [comment]
It some how fixed itself between updates at least for my modpack AQM2. Another person discovered data attributes was the cause for their pack. I'll link the issue later, it's on the extra origins repo
